-- ===========================================================================
-- V1 - Core reference data: identities and the physical venue hierarchy.
--
--   cities -> theaters -> screens -> seats
--
-- All primary keys are UUIDv7 values generated by the application
-- (Hibernate @UuidGenerator(algorithm = UuidVersion7Strategy.class)). v7 is
-- time-ordered, so inserts stay at the right-hand edge of the B-tree instead
-- of scattering random pages the way UUIDv4 does.
--
-- All timestamps are TIMESTAMPTZ and are always written as UTC instants.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------------
CREATE TABLE users
(
    id            UUID         NOT NULL,
    username      VARCHAR(100) NOT NULL,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    full_name     VARCHAR(150) NOT NULL,
    phone_number  VARCHAR(20),
    role          VARCHAR(20)  NOT NULL,
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL,
    updated_at    TIMESTAMPTZ  NOT NULL,

    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('ADMIN', 'CUSTOMER'))
);

-- ---------------------------------------------------------------------------
-- cities
--
-- time_zone matters for correctness, not presentation: "weekend pricing" is
-- decided by the local calendar day of the show, not by the UTC day.
-- ---------------------------------------------------------------------------
CREATE TABLE cities
(
    id         UUID         NOT NULL,
    name       VARCHAR(120) NOT NULL,
    state      VARCHAR(120) NOT NULL,
    country    VARCHAR(80)  NOT NULL,
    time_zone  VARCHAR(60)  NOT NULL,
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ  NOT NULL,
    updated_at TIMESTAMPTZ  NOT NULL,

    CONSTRAINT pk_cities PRIMARY KEY (id),
    CONSTRAINT uq_cities_name_state UNIQUE (name, state)
);

CREATE INDEX ix_cities_active ON cities (active);

-- ---------------------------------------------------------------------------
-- movies
--
-- A show is a screening *of something*; modelling it as its own table avoids
-- de-normalising the title onto every show row.
-- ---------------------------------------------------------------------------
CREATE TABLE movies
(
    id               UUID         NOT NULL,
    title            VARCHAR(200) NOT NULL,
    language         VARCHAR(50)  NOT NULL,
    certification    VARCHAR(10),
    duration_minutes INTEGER      NOT NULL,
    release_date     DATE,
    synopsis         TEXT,
    active           BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMPTZ  NOT NULL,
    updated_at       TIMESTAMPTZ  NOT NULL,

    CONSTRAINT pk_movies PRIMARY KEY (id),
    CONSTRAINT uq_movies_title_language UNIQUE (title, language),
    CONSTRAINT ck_movies_duration_positive CHECK (duration_minutes > 0)
);

-- ---------------------------------------------------------------------------
-- theaters
-- ---------------------------------------------------------------------------
CREATE TABLE theaters
(
    id         UUID         NOT NULL,
    city_id    UUID         NOT NULL,
    name       VARCHAR(150) NOT NULL,
    address    VARCHAR(300) NOT NULL,
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ  NOT NULL,
    updated_at TIMESTAMPTZ  NOT NULL,

    CONSTRAINT pk_theaters PRIMARY KEY (id),
    CONSTRAINT fk_theaters_city FOREIGN KEY (city_id) REFERENCES cities (id),
    CONSTRAINT uq_theaters_city_name UNIQUE (city_id, name)
);

CREATE INDEX ix_theaters_city ON theaters (city_id);

-- ---------------------------------------------------------------------------
-- screens
-- ---------------------------------------------------------------------------
CREATE TABLE screens
(
    id          UUID         NOT NULL,
    theater_id  UUID         NOT NULL,
    name        VARCHAR(100) NOT NULL,
    screen_type VARCHAR(30)  NOT NULL,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL,
    updated_at  TIMESTAMPTZ  NOT NULL,

    CONSTRAINT pk_screens PRIMARY KEY (id),
    CONSTRAINT fk_screens_theater FOREIGN KEY (theater_id) REFERENCES theaters (id),
    CONSTRAINT uq_screens_theater_name UNIQUE (theater_id, name),
    CONSTRAINT ck_screens_type CHECK (screen_type IN ('STANDARD', 'IMAX', 'FOUR_DX', 'RECLINER'))
);

CREATE INDEX ix_screens_theater ON screens (theater_id);

-- ---------------------------------------------------------------------------
-- seats
--
-- The physical seat layout of a screen. Immutable reference data once shows
-- exist: show_seats snapshots the inventory per show.
-- ---------------------------------------------------------------------------
CREATE TABLE seats
(
    id          UUID        NOT NULL,
    screen_id   UUID        NOT NULL,
    row_label   VARCHAR(5)  NOT NULL,
    seat_number INTEGER     NOT NULL,
    category    VARCHAR(20) NOT NULL,
    active      BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL,

    CONSTRAINT pk_seats PRIMARY KEY (id),
    CONSTRAINT fk_seats_screen FOREIGN KEY (screen_id) REFERENCES screens (id),
    CONSTRAINT uq_seats_screen_row_number UNIQUE (screen_id, row_label, seat_number),
    CONSTRAINT ck_seats_number_positive CHECK (seat_number > 0),
    CONSTRAINT ck_seats_category CHECK (category IN ('REGULAR', 'PREMIUM'))
);

CREATE INDEX ix_seats_screen ON seats (screen_id);
